namespace PMDA_API.Models
{
    public class MasterPMDARecords
    {
        public TimeSpan UTC_Time { get; set; }
        public TimeSpan Time { get; set; }
        public long MilliSecond { get; set; }

        #region Class for Threat Data
        public int ThreatCount { get; set; }
        public string Threat_1_Threat_Presence { get; set; }
        public int    Threat_1_ThreatSymbolCode { get; set; }
        public int    Threat_1_ThreatAltSymbolcode { get; set; }
        public string Threat_1_ThreatName { get; set; }
        public string Threat_1_ThreatSymFGColour { get; set; }
        public string Threat_1_ThreatSymBGColour { get; set; }
        public string Threat_1_CircleAttribute { get; set; }
        public string Threat_1_SquareAttribute { get; set; }
        public string Threat_1_MoustacheAttribute { get; set; }
        public string Threat_1_DiamondAttribure { get; set; }
        public string Threat_1_DisplayStatus { get; set; }
        public string Threat_1_BlinkStatus { get; set; }
        public string Threat_1_MDTStatus { get; set; }
        public decimal Threat_1_Azimuth { get; set; }
        public int Threat_1_ThreatRange { get; set; }


        public string Threat_2_Threat_Presence { get; set; }
        public int Threat_2_ThreatSymbolCode { get; set; }
        public int Threat_2_ThreatAltSymbolcode { get; set; }
        public string Threat_2_ThreatName { get; set; }
        public string Threat_2_ThreatSymFGColour { get; set; }
        public string Threat_2_ThreatSymBGColour { get; set; }
        public string Threat_2_CircleAttribute { get; set; }
        public string Threat_2_SquareAttribute { get; set; }
        public string Threat_2_MoustacheAttribute { get; set; }
        public string Threat_2_DiamondAttribure { get; set; }
        public string Threat_2_DisplayStatus { get; set; }
        public string Threat_2_BlinkStatus { get; set; }
        public string Threat_2_MDTStatus { get; set; }
        public decimal Threat_2_Azimuth { get; set; }
        public int Threat_2_ThreatRange { get; set; }

        public string Threat_3_Threat_Presence { get; set; }
        public int Threat_3_ThreatSymbolCode { get; set; }
        public int Threat_3_ThreatAltSymbolcode { get; set; }
        public string Threat_3_ThreatName { get; set; }
        public string Threat_3_ThreatSymFGColour { get; set; }
        public string Threat_3_ThreatSymBGColour { get; set; }
        public string Threat_3_CircleAttribute { get; set; }
        public string Threat_3_SquareAttribute { get; set; }
        public string Threat_3_MoustacheAttribute { get; set; }
        public string Threat_3_DiamondAttribure { get; set; }
        public string Threat_3_DisplayStatus { get; set; }
        public string Threat_3_BlinkStatus { get; set; }
        public string Threat_3_MDTStatus { get; set; }
        public decimal Threat_3_Azimuth { get; set; }
        public int Threat_3_ThreatRange { get; set; }


        public string Threat_4_Threat_Presence { get; set; }
        public int Threat_4_ThreatSymbolCode { get; set; }
        public int Threat_4_ThreatAltSymbolcode { get; set; }
        public string Threat_4_ThreatName { get; set; }
        public string Threat_4_ThreatSymFGColour { get; set; }
        public string Threat_4_ThreatSymBGColour { get; set; }
        public string Threat_4_CircleAttribute { get; set; }
        public string Threat_4_SquareAttribute { get; set; }
        public string Threat_4_MoustacheAttribute { get; set; }
        public string Threat_4_DiamondAttribure { get; set; }
        public string Threat_4_DisplayStatus { get; set; }
        public string Threat_4_BlinkStatus { get; set; }
        public string Threat_4_MDTStatus { get; set; }
        public decimal Threat_4_Azimuth { get; set; }
        public int Threat_4_ThreatRange { get; set; }


        public string Threat_5_Threat_Presence { get; set; }
        public int Threat_5_ThreatSymbolCode { get; set; }
        public int Threat_5_ThreatAltSymbolcode { get; set; }
        public string Threat_5_ThreatName { get; set; }
        public string Threat_5_ThreatSymFGColour { get; set; }
        public string Threat_5_ThreatSymBGColour { get; set; }
        public string Threat_5_CircleAttribute { get; set; }
        public string Threat_5_SquareAttribute { get; set; }
        public string Threat_5_MoustacheAttribute { get; set; }
        public string Threat_5_DiamondAttribure { get; set; }
        public string Threat_5_DisplayStatus { get; set; }
        public string Threat_5_BlinkStatus { get; set; }
        public string Threat_5_MDTStatus { get; set; }
        public decimal Threat_5_Azimuth { get; set; }
        public int Threat_5_ThreatRange { get; set; }


        public string Threat_6_Threat_Presence { get; set; }
        public int Threat_6_ThreatSymbolCode { get; set; }
        public int Threat_6_ThreatAltSymbolcode { get; set; }
        public string Threat_6_ThreatName { get; set; }
        public string Threat_6_ThreatSymFGColour { get; set; }
        public string Threat_6_ThreatSymBGColour { get; set; }
        public string Threat_6_CircleAttribute { get; set; }
        public string Threat_6_SquareAttribute { get; set; }
        public string Threat_6_MoustacheAttribute { get; set; }
        public string Threat_6_DiamondAttribure { get; set; }
        public string Threat_6_DisplayStatus { get; set; }
        public string Threat_6_BlinkStatus { get; set; }
        public string Threat_6_MDTStatus { get; set; }
        public decimal Threat_6_Azimuth { get; set; }
        public int Threat_6_ThreatRange { get; set; }

        public string Threat_7_Threat_Presence { get; set; }
        public int Threat_7_ThreatSymbolCode { get; set; }
        public int Threat_7_ThreatAltSymbolcode { get; set; }
        public string Threat_7_ThreatName { get; set; }
        public string Threat_7_ThreatSymFGColour { get; set; }
        public string Threat_7_ThreatSymBGColour { get; set; }
        public string Threat_7_CircleAttribute { get; set; }
        public string Threat_7_SquareAttribute { get; set; }
        public string Threat_7_MoustacheAttribute { get; set; }
        public string Threat_7_DiamondAttribure { get; set; }
        public string Threat_7_DisplayStatus { get; set; }
        public string Threat_7_BlinkStatus { get; set; }
        public string Threat_7_MDTStatus { get; set; }
        public decimal Threat_7_Azimuth { get; set; }
        public int Threat_7_ThreatRange { get; set; }

        public string Threat_8_Threat_Presence { get; set; }
        public int Threat_8_ThreatSymbolCode { get; set; }
        public int Threat_8_ThreatAltSymbolcode { get; set; }
        public string Threat_8_ThreatName { get; set; }
        public string Threat_8_ThreatSymFGColour { get; set; }
        public string Threat_8_ThreatSymBGColour { get; set; }
        public string Threat_8_CircleAttribute { get; set; }
        public string Threat_8_SquareAttribute { get; set; }
        public string Threat_8_MoustacheAttribute { get; set; }
        public string Threat_8_DiamondAttribure { get; set; }
        public string Threat_8_DisplayStatus { get; set; }
        public string Threat_8_BlinkStatus { get; set; }
        public string Threat_8_MDTStatus { get; set; }
        public decimal Threat_8_Azimuth { get; set; }
        public int Threat_8_ThreatRange { get; set; }

        public string Threat_9_Threat_Presence { get; set; }
        public int Threat_9_ThreatSymbolCode { get; set; }
        public int Threat_9_ThreatAltSymbolcode { get; set; }
        public string Threat_9_ThreatName { get; set; }
        public string Threat_9_ThreatSymFGColour { get; set; }
        public string Threat_9_ThreatSymBGColour { get; set; }
        public string Threat_9_CircleAttribute { get; set; }
        public string Threat_9_SquareAttribute { get; set; }
        public string Threat_9_MoustacheAttribute { get; set; }
        public string Threat_9_DiamondAttribure { get; set; }
        public string Threat_9_DisplayStatus { get; set; }
        public string Threat_9_BlinkStatus { get; set; }
        public string Threat_9_MDTStatus { get; set; }
        public decimal Threat_9_Azimuth { get; set; }
        public int Threat_9_ThreatRange { get; set; }


        public string Threat_10_Threat_Presence { get; set; }
        public int Threat_10_ThreatSymbolCode { get; set; }
        public int Threat_10_ThreatAltSymbolcode { get; set; }
        public string Threat_10_ThreatName { get; set; }
        public string Threat_10_ThreatSymFGColour { get; set; }
        public string Threat_10_ThreatSymBGColour { get; set; }
        public string Threat_10_CircleAttribute { get; set; }
        public string Threat_10_SquareAttribute { get; set; }
        public string Threat_10_MoustacheAttribute { get; set; }
        public string Threat_10_DiamondAttribure { get; set; }
        public string Threat_10_DisplayStatus { get; set; }
        public string Threat_10_BlinkStatus { get; set; }
        public string Threat_10_MDTStatus { get; set; }


        public string Threat_11_Threat_Presence { get; set; }
        public int Threat_11_ThreatSymbolCode { get; set; }
        public int Threat_11_ThreatAltSymbolcode { get; set; }
        public string Threat_11_ThreatName { get; set; }
        public string Threat_11_ThreatSymFGColour { get; set; }
        public string Threat_11_ThreatSymBGColour { get; set; }
        public string Threat_11_CircleAttribute { get; set; }
        public string Threat_11_SquareAttribute { get; set; }
        public string Threat_11_MoustacheAttribute { get; set; }
        public string Threat_11_DiamondAttribure { get; set; }
        public string Threat_11_DisplayStatus { get; set; }
        public string Threat_11_BlinkStatus { get; set; }
        public string Threat_11_MDTStatus { get; set; }
        public decimal Threat_11_Azimuth { get; set; }
        public int Threat_11_ThreatRange { get; set; }


        public string Threat_12_Threat_Presence { get; set; }
        public int Threat_12_ThreatSymbolCode { get; set; }
        public int Threat_12_ThreatAltSymbolcode { get; set; }
        public string Threat_12_ThreatName { get; set; }
        public string Threat_12_ThreatSymFGColour { get; set; }
        public string Threat_12_ThreatSymBGColour { get; set; }
        public string Threat_12_CircleAttribute { get; set; }
        public string Threat_12_SquareAttribute { get; set; }
        public string Threat_12_MoustacheAttribute { get; set; }
        public string Threat_12_DiamondAttribure { get; set; }
        public string Threat_12_DisplayStatus { get; set; }
        public string Threat_12_BlinkStatus { get; set; }
        public string Threat_12_MDTStatus { get; set; }
        public decimal Threat_12_Azimuth { get; set; }
        public int Threat_12_ThreatRange { get; set; }


        public string Threat_13_Threat_Presence { get; set; }
        public int Threat_13_ThreatSymbolCode { get; set; }
        public int Threat_13_ThreatAltSymbolcode { get; set; }
        public string Threat_13_ThreatName { get; set; }
        public string Threat_13_ThreatSymFGColour { get; set; }
        public string Threat_13_ThreatSymBGColour { get; set; }
        public string Threat_13_CircleAttribute { get; set; }
        public string Threat_13_SquareAttribute { get; set; }
        public string Threat_13_MoustacheAttribute { get; set; }
        public string Threat_13_DiamondAttribure { get; set; }
        public string Threat_13_DisplayStatus { get; set; }
        public string Threat_13_BlinkStatus { get; set; }
        public string Threat_13_MDTStatus { get; set; }
        public decimal Threat_13_Azimuth { get; set; }
        public int Threat_13_ThreatRange { get; set; }


        public string Threat_14_Threat_Presence { get; set; }
        public int Threat_14_ThreatSymbolCode { get; set; }
        public int Threat_14_ThreatAltSymbolcode { get; set; }
        public string Threat_14_ThreatName { get; set; }
        public string Threat_14_ThreatSymFGColour { get; set; }
        public string Threat_14_ThreatSymBGColour { get; set; }
        public string Threat_14_CircleAttribute { get; set; }
        public string Threat_14_SquareAttribute { get; set; }
        public string Threat_14_MoustacheAttribute { get; set; }
        public string Threat_14_DiamondAttribure { get; set; }
        public string Threat_14_DisplayStatus { get; set; }
        public string Threat_14_BlinkStatus { get; set; }
        public string Threat_14_MDTStatus { get; set; }
        public decimal Threat_14_Azimuth { get; set; }
        public int Threat_14_ThreatRange { get; set; }



        public string Threat_15_Threat_Presence { get; set; }
        public int Threat_15_ThreatSymbolCode { get; set; }
        public int Threat_15_ThreatAltSymbolcode { get; set; }
        public string Threat_15_ThreatName { get; set; }
        public string Threat_15_ThreatSymFGColour { get; set; }
        public string Threat_15_ThreatSymBGColour { get; set; }
        public string Threat_15_CircleAttribute { get; set; }
        public string Threat_15_SquareAttribute { get; set; }
        public string Threat_15_MoustacheAttribute { get; set; }
        public string Threat_15_DiamondAttribure { get; set; }
        public string Threat_15_DisplayStatus { get; set; }
        public string Threat_15_BlinkStatus { get; set; }
        public string Threat_15_MDTStatus { get; set; }
        public decimal Threat_15_Azimuth { get; set; }
        public int Threat_15_ThreatRange { get; set; }

        public string Threat_16_Threat_Presence { get; set; }
        public int Threat_16_ThreatSymbolCode { get; set; }
        public int Threat_16_ThreatAltSymbolcode { get; set; }
        public string Threat_16_ThreatName { get; set; }
        public string Threat_16_ThreatSymFGColour { get; set; }
        public string Threat_16_ThreatSymBGColour { get; set; }
        public string Threat_16_CircleAttribute { get; set; }
        public string Threat_16_SquareAttribute { get; set; }
        public string Threat_16_MoustacheAttribute { get; set; }
        public string Threat_16_DiamondAttribure { get; set; }
        public string Threat_16_DisplayStatus { get; set; }
        public string Threat_16_BlinkStatus { get; set; }
        public string Threat_16_MDTStatus { get; set; }
        public decimal Threat_16_Azimuth { get; set; }
        public int Threat_16_ThreatRange { get; set; }
        #endregion
        public string INS_Pram_Valid { get; set; }
        public string Baro_Altitude_Valid { get; set; }
        public string Radio_HI_Valid { get; set; }
        public string GPS_Data_Valid { get; set; }
        public string Ac_On_GND_Status { get; set; }
        public string CMDS_Presence { get; set; }
        public decimal TrueHeading_pi_rad { get; set; }
        public decimal PitchAngle_pi_rad { get; set; }
        public decimal RollAngle_pi_rad { get; set; }
        public decimal PresentPosLatitude { get; set; }
        public decimal PresentPosLongitude { get; set; }
        public decimal XVelocity { get; set; }
        public decimal YVelocity { get; set; }
        public decimal ZVelocity { get; set; }
        public decimal PitchRate_pi_rad_s { get; set; }
        public decimal RollRate_pi_rad_s { get; set; }
        public decimal YawRate_pi_rad_s { get; set; }
        public int RadioHeight_m { get; set; }
        public int BaroAltitude { get; set; }
        public int GPS_Yday { get; set; }
        public int GPS_Hour { get; set; }
        public int GPS_Minute { get; set; }
        public int GPS_Seconds { get; set; }
        public decimal Altitude { get; set; }
        public decimal YAW_Angle { get; set; }

        public int Track_Id { get; set; }
        public int HitCount { get; set; }
        public int SymbolCode { get; set; }
        public decimal Frequency { get; set; }
        public decimal PulseWidth { get; set; }
        public decimal Amplitude { get; set; }
        public decimal AOA { get; set; }
        public decimal DOA { get; set; }
        public decimal Lattitude { get; set; }
        public decimal Longitude { get; set; }
        public decimal TrueHeading { get; set; }
        public int Altitude_m { get; set; }
        public decimal RollAngle { get; set; }
        public decimal PitchRate { get; set; }
        public decimal YawRate { get; set; }
        public string Weaponid { get; set; }
        public string WeaponDescription { get; set; }
        public string EmitterId { get; set; }
        public string EmitterDescription { get; set; }
        public string ModeId { get; set; }
        public string ModeDescription { get; set; }
        public string EmitterRange { get; set; }
        public string PRI_1 { get; set; }
        public string PRI_2 { get; set; }
        public string PRI_3 { get; set; }
        public string PRI_4 { get; set; }
        public string PRI_5 { get; set; }
        public string PRI_6 { get; set; }
        public string PRI_7 { get; set; }
        public string PRI_8 { get; set; }
        public string PRI_9 { get; set; }
        public string PRI_10 { get; set; }
        public string PRI_11 { get; set; }
        public string PRI_12 { get; set; }
        public string PRI_13 { get; set; }
        public string PRI_14 { get; set; }
        public string PRI_15 { get; set; }
        public string PRI_16 { get; set; }
        public string PRI_17 { get; set; }
        public string PRI_18 { get; set; }
        public string PRI_19 { get; set; }
        public string PRI_20 { get; set; }
        public string PRI_21 { get; set; }
        public string PRI_22 { get; set; }
        public string PRI_23 { get; set; }
        public string PRI_24 { get; set; }
        public string PRI_25 { get; set; }
        public string PRI_26 { get; set; }
        public string PRI_27 { get; set; }
        public string PRI_28 { get; set; }
        public string PRI_29 { get; set; }
        public string PRI_30 { get; set; }
        public string PRI_31 { get; set; }
        public string PRI_32 { get; set; }
        public string PRI_33 { get; set; }
        public string PRI_34 { get; set; }
        public string PRI_35 { get; set; }
        public string PRI_36 { get; set; }
        public string PRI_37 { get; set; }
        public string PRI_38 { get; set; }
        public string PRI_39 { get; set; }
        public string PRI_40 { get; set; }
        public string PRI_41 { get; set; }
        public string PRI_42 { get; set; }
        public string PRI_43 { get; set; }
        public string PRI_44 { get; set; }
        public string PRI_45 { get; set; }
        public string PRI_46 { get; set; }
        public string PRI_47 { get; set; }
        public string PRI_48 { get; set; }
        public string PRI_49 { get; set; }
        public string PRI_50 { get; set; }
        public string PRI_51 { get; set; }
        public string PRI_52 { get; set; }
        public string PRI_53 { get; set; }
        public string PRI_54 { get; set; }
        public string PRI_55 { get; set; }
        public string PRI_56 { get; set; }
        public string PRI_57 { get; set; }
        public string PRI_58 { get; set; }
        public string PRI_59 { get; set; }
        public string PRI_60 { get; set; }
        public string PRI_61 { get; set; }
        public string PRI_62 { get; set; }
        public string PRI_63 { get; set; }
        public string PRI_64 { get; set; }
        public string RDR_Tx_Band { get; set; }
        public string RDR_Radar_Transmission { get; set; }
        public string RDR_Health_Status { get; set; }
        public string EraseSelect { get; set; }
        public string RDR_RadarMode { get; set; }
        public string RDR_MinorMode { get; set; }
    }
}
